apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  namespace: rently-showings-monitor
type: Opaque
stringData:
  POSTGRES_DB: rently
  POSTGRES_USER: rently
  POSTGRES_PASSWORD: REPLACE_ME


