apiVersion: v1
kind: Service
metadata:
  name: rently-showings-monitor
  namespace: rently-showings-monitor
spec:
  selector:
    app: rently-showings-monitor
  ports:
    - name: http
      port: 80
      targetPort: 8080


