apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rently-showings-monitor
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: rently-showings-monitor
  source:
    # TODO: set this to the Git URL Argo CD can reach (GitHub/GitLab/etc).
    # Example: https://github.com/<you>/rently-showings-monitor.git
    repoURL: REPLACE_WITH_YOUR_GIT_REPO_URL
    targetRevision: main
    path: k8s/rently-showings-monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


